### ISSUE TITLE
Website Not Working.

### ISSUE THREAD

**Issue by CodingSpecies** [devcreatives/first_contribution#91]
Hello, the website link for this repo is not working. When I press it, it leads to this message:
![image](https://user-images.githubusercontent.com/70807500/126174911-a23e960b-325e-4415-b337-e28710bb3d9a.png)

`Internal Server Error`.
Thank you.

**Comment by MRslimcoder** [comment]
@CodingSpecies Website is working fine, unable to reproduce this issue.
